### ISSUE TITLE
Currently doesn't work in Qtile

### ISSUE THREAD

**Issue by jonathan-raines** [sffjunkie/qtile-openweathermap#1]
2 errors in **owm.py** 

1. Module 'libqtile.widget.base' has no 'ThreadedPollText' member
2. Access to member 'icon_font' before its definition on line 143

I noticed that widget.base has a member called ThreadedPoolText so I tried changing that. It cleared the error but did not work. When importing owm and created a widget with owm.OpenWeatherMap(), I can not restart qtile to see the widget.

I'm currently using Arch Linux

**Comment by sffjunkie** [comment]
Thanks for the report. I have pushed a v0.2 which should fix the problem.

The problem was that the QTile project have removed `ThreadedPollText` from recent versions and used `ThreadPoolText` instead. It has a required `text` parameter so you need to pass that to the `ThreadPoolText`\'s `__init__`

The second item should not be an error, even though a linter thinks it is a problem as the `add_default` method adds it.
